### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by alirezaniki** [emolch/kiwi#17]
Hi Dear Emolch
Sometimes when The FILTER_NOISY value is set to True KIWI gives the following error:

Traceback (most recent call last):
  File "./rapidinv", line 7741, in <module>
    prepData(inv_step,inv_param,traces,apply_taper)
  File "./rapidinv", line 1039, in prepData
    checkDataQuality(inv_step,inv_param,traces,freceivers,fdata)
  File "./rapidinv", line 1002, in checkDataQuality
    ncoef2.append(float(splittedline12[i*2+1])/float(splittedline11[i*2+1]))
ZeroDivisionError: float division by zero

Why this is happening? Whats that suppose to mean?
Kind Regards.

**Comment by alirezaniki** [comment]
I figured out that the error depends on the allowed maximum distance of stations. when I decreased it from 1500 to 1300 the error just gone!
But still have no idea why this error pups up!
