### ISSUE TITLE
MT Solution Error.

### ISSUE THREAD

**Issue by NimaDolatabadi** [emolch/kiwi#20]
while running `./rapidinv rapidinv.inp.synth1` it completely do the job for `ptsolution` but it gives an error while calculation `mtsolution`. the error is shown below:

```
Analysing results inversion step 1...
check number of mt solutions: 29
HEY! best MT solutions are 2
Calculating synthetic seismograms...
Calling minimizer ../RESULTS/SYNTH2/minimizer.inp1-bestmt
1 ../RESULTS/SYNTH2/minimizer.inp1-bestmt ../RESULTS/SYNTH2/minimizer.out1-bestmt
2 minimizer < ../RESULTS/SYNTH2/minimizer.inp1-bestmt > ../RESULTS/SYNTH2/minimizer.out1-bestmt
Plotting results inversion step 1...
M11 0.859078632029 -0.919304575288 -0.633886918302
 standard decomposition: MT = Miso + Mdc + Mclvd 
EW -0.3558331157379283 1.1676277422971997
F 0.3047487678203496
Traceback (most recent call last):
  File "./rapidinv", line 7757, in <module>
    plotMTSolution(inv_step,inv_param,bestdc,mt_solutions_1,best_mt_solutions_1,traces)
  File "./rapidinv", line 4893, in plotMTSolution
    clvd=mt.get_CLVD()
  File "modules/mopad.py", line 1299, in get_CLVD
    if self._CLVD ==None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
How can this problem be solved?

**Comment by NimaDolatabadi** [comment]
I was able to debug this code on my own too.
I will report it here but before that I'm attaching a full list of packages using conda2 in which it is needed as a dependency of KIWI software.

[conda2-list.txt](https://github.com/emolch/kiwi/files/3897195/conda2-list.txt)

in `mopad.py` the following lines of **1299** and **1323** that are shown below"
`if self._CLVD ==None:` and `if self._CLVD is None:`
were changed to:
`if self._CLVD is None:` and `if self._CLVD is None:`

This actually did the trick with no error at all. It could be a **BUG**, if not, Please let me know.
@emolch @moscardo

**Comment by NimaDolatabadi** [comment]
I have read the new `mopad.py` and it still needs this correction.
I have attached the picture of the code and line numbers.
![Screenshot from 2019-12-01 15-36-49](https://user-images.githubusercontent.com/32169409/69913708-8f292900-1450-11ea-8ed8-f01f794f5fac.png)
